include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - 'build/**'
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
  errors:
    unused_element: warning
    unused_field: warning
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning

linter:
  rules:
    # Bonnes pratiques
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_print
    - avoid_renaming_method_parameters
    - avoid_returning_null
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    
    # Sécurité
    - close_sinks
    - unnecessary_overrides