name: motiv_educ  
description: Application de prédiction étudiante ORIEX
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon: false
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 55
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/